services:
  api-test:
    image: test-api-restassured
    build: .
    volumes:
      - ./allure-results:/app/target/allure-results
      - ./target/surefire-reports:/app/target/surefire-reports
