version: '3'

services:
   api-test:
      image: test-api-restassured
      build:
         context: .
         dockerfile: Dockerfile
         volumes:
           - ./API-RestAssured/allure-results:/app/allure-results
           