pipeline {
    agent any

    options {
        ansiColor('xterm')
        timeout(time: 20, unit: 'MINUTES')
    }
    
    stages {
        stage('Build') {
            steps {      
                // Clean before build
                cleanWs( deleteDirs: true, disableDeferredWipeout: true)
                // We need to explicitly checkout from SCM here
                checkout scm
                sh 'docker-compose -f API-RestAssured/docker-compose.yml build'
            }
        }

        stage('Test and Report') {
            steps {
                echo 'running tests'
                sh 'docker-compose -f API-RestAssured/docker-compose.yml run --rm api-test mvn test'
            }
        }
    }

    post {
        always{
                script{
                        allure([
                                includeProperties: false, 
                                jdk: '', 
                                reportBuildPolicy: 'ALWAYS',
                                results: [[path: 'allure-results']],
                                report: 'allure-report'
                        ])
                    }
            } 
    }
}