name: Tests API CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build-image.outputs.image-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Build Docker
        id: build-image
        run: |
          docker-compose build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Use Docker Compose to pull and run
        run: |
          docker-compose up -d
          docker-compose run --rm api-test mvn test -ntp

      - name: Tear down Docker Compose
        run: docker-compose down

  report:
    runs-on: ubuntu-latest
    needs: test
    if: always()
    continue-on-error: true
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Load test report history
        uses: actions/checkout@v3
        with:
          ref: report-allure
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: report-allure
          publish_dir: allure-history